### ISSUE TITLE
Tests for handling data from HEADER tags

### ISSUE THREAD

**Issue by AdrianMontaguSmartDCSIT** [xtuml/otel2puml#82]
Tests for processing HEADER tags when used within span field_mapping.

The following functions to be tested:

- handle_data_from_header
- find_matching_header_value
- get_value_type
- add_or_append_value

Outcomes:

- Tests written
- Tests pass
- Tests reviewed and accepted

**Comment by FreddieMatherSmartDCSIT** [comment]
Due to other functionality being developed this testing is not required now.
